# BANCO DE DADOS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# CONFIGURAÇÃO DE PORTA DO RENDER
server.port=${PORT:8080}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000